/**
 * YouTube 字幕解析纯函数 —— 不依赖 DOM / fetch,便于单元测试。
 * 探针验证的路径(technical-spike.md §1.3, §1.5):
 *
 * - track 元数据:ytInitialPlayerResponse.captions.playerCaptionsTracklistRenderer.captionTracks
 * - get_transcript params:ytInitialData.engagementPanels[].getTranscriptEndpoint.params
 * - cue 响应路径:actions[0].updateEngagementPanelAction.content.transcriptRenderer
 *                .content.transcriptSearchPanelRenderer.body.transcriptSegmentListRenderer
 *                .initialSegments[].transcriptSegmentRenderer
 */

import type { CaptionTrackSummary, RawCaptionTrack } from '../shared/types.js';

/**
 * 从原始 track 元数据生成 summary。探针:kind === 'asr' 即 ASR。
 */
export function toTrackSummary(
  raw: RawCaptionTrack,
  index: number,
): CaptionTrackSummary {
  return {
    id: `track-${index}-${raw.languageCode}-${raw.kind ?? 'manual'}`,
    languageCode: raw.languageCode,
    label: raw.name ?? raw.languageCode,
    isAutoGenerated: raw.kind === 'asr',
  };
}

/**
 * 从 track summary 重生成 id(保证 listTracks 和 loadTrack 用同一个 id 体系)。
 */
export function trackIdOf(
  languageCode: string,
  isAutoGenerated: boolean,
  index: number,
): string {
  return `track-${index}-${languageCode}-${isAutoGenerated ? 'asr' : 'manual'}`;
}

/**
 * 从原始 track 列表按偏好选首选轨道。
 * 1.0 策略(spec 未明确,探针决策):同语言优先人工 > ASR。
 * 无任何轨道返回 null。
 */
export function pickPreferredTrack(
  tracks: readonly RawCaptionTrack[],
  languageCode = 'en',
): { track: RawCaptionTrack; index: number } | null {
  const matches = tracks
    .map((track, index) => ({ track, index }))
    .filter(({ track }) => track.languageCode === languageCode);

  if (matches.length === 0) return null;

  // 人工优先(kind 非 asr)
  const manual = matches.find(({ track }) => track.kind !== 'asr');
  if (manual) return manual;
  return matches[0];
}

/**
 * get_transcript 响应的 cue 项结构(最小必要字段)。
 */
interface TranscriptSegment {
  transcriptSegmentRenderer?: {
    startMs?: string;
    endMs?: string;
    snippet?: { runs?: Array<{ text?: string }> };
  };
}

/**
 * get_transcript 响应的最小结构(只取解析 cue 需要的路径)。
 */
interface GetTranscriptResponse {
  actions?: Array<{
    updateEngagementPanelAction?: {
      content?: {
        transcriptRenderer?: {
          content?: {
            transcriptSearchPanelRenderer?: {
              body?: {
                transcriptSegmentListRenderer?: {
                  initialSegments?: TranscriptSegment[];
                };
              };
            };
          };
        };
      };
    };
    // 兜底路径(探针发现部分响应可能走 reloadContinuationItemsCommand)
    reloadContinuationItemsCommand?: {
      continuationItems?: TranscriptSegment[];
    };
  }>;
}

/**
 * 从 get_transcript 响应解析出原始 cue(未规范化)。
 * 支持探针发现的两个路径:主路径 + reloadContinuationItemsCommand 兜底。
 */
export function parseTranscriptResponse(
  response: unknown,
): Array<{ startMs: number; endMs: number; text: string }> {
  const data = response as GetTranscriptResponse;
  if (!data?.actions?.length) return [];

  let segments: TranscriptSegment[] | undefined;

  for (const action of data.actions) {
    // 主路径:transcriptRenderer.content.transcriptSearchPanelRenderer.body...
    const main = action?.updateEngagementPanelAction?.content?.transcriptRenderer
      ?.content?.transcriptSearchPanelRenderer?.body?.transcriptSegmentListRenderer
      ?.initialSegments;
    if (main?.length) {
      segments = main;
      break;
    }
    // 兜底路径
    const fallback = action?.reloadContinuationItemsCommand?.continuationItems;
    if (fallback?.length) {
      segments = fallback;
      break;
    }
  }

  if (!segments) return [];

  const cues: Array<{ startMs: number; endMs: number; text: string }> = [];
  for (const seg of segments) {
    const r = seg.transcriptSegmentRenderer;
    if (!r) continue;
    const startMs = parseMs(r.startMs);
    const endMs = parseMs(r.endMs);
    const text = r.snippet?.runs?.map((run) => run.text ?? '').join('').trim() ?? '';
    if (Number.isFinite(startMs) && Number.isFinite(endMs) && text) {
      cues.push({ startMs, endMs, text });
    }
  }
  return cues;
}

function parseMs(value: string | undefined): number {
  if (!value) return NaN;
  const n = Number(value);
  return Number.isFinite(n) ? n : NaN;
}
