/**
 * nosub 核心数据模型。
 * 对应 design.md §4,所有播放计算统一用毫秒。
 */

/**
 * 一条字幕 cue。会话内 id 稳定,不要求跨视频稳定。
 * 时间单位:毫秒。
 */
export interface Cue {
  id: string;
  startMs: number;
  endMs: number;
  text: string;
  /** 可选翻译;无翻译时为 undefined */
  translatedText?: string;
  /** 翻译失败原因: undefined=未尝试, string=失败原因(如"网络超时") */
  translationFailed?: string;
}

/**
 * 字幕轨道。一条轨道对应一种语言/来源。
 */
export interface CaptionTrack {
  id: string;
  languageCode: string;
  label: string;
  /** 自动生成(ASR)还是人工字幕。探针确认:track.kind === 'asr' 即 ASR */
  isAutoGenerated: boolean;
  cues: Cue[];
}

/**
 * 字幕轨道的摘要,不含 cue 数据。用于 listTracks 展示。
 */
export interface CaptionTrackSummary {
  id: string;
  languageCode: string;
  label: string;
  isAutoGenerated: boolean;
}

/**
 * 字幕轨道的原始元数据,从 YouTube 页面读出,尚未转换为 CaptionTrack。
 * 对应探针发现的 ytInitialPlayerResponse.captions.captionTracks 项。
 */
export interface RawCaptionTrack {
  languageCode: string;
  /** 'asr' 表示自动生成;人工字幕此字段不存在(undefined) */
  kind?: string;
  /** 用户可见的轨道名,如 "English (auto-generated)" */
  name?: string;
  /** timedtext baseUrl —— 探针证实此路不通(缺 PO Token),保留字段供未来复用 */
  baseUrl?: string;
}

/**
 * 用户设置。design §10。
 */
export interface UserSettings {
  /** 插件是否启用 */
  enabled: boolean;
  showTargetCaption: boolean;
  showTranslatedCaption: boolean;
  /** 目标语言(字幕语言),默认 'en' */
  targetLanguage?: string;
  /** 翻译语言,默认用户系统语言或 'zh-CN' */
  translationLanguage?: string;
  /** Extension interface language. auto follows the browser UI language. */
  interfaceLanguage: 'auto' | 'en' | 'zh_CN';
  /** Dictionary lookup route. Public APIs always fall back to the NoSub server. */
  dictionarySource: 'public' | 'server';
}

/**
 * 收藏的单词。design §4。
 */
export interface VocabularyItem {
  id: string;
  word: string;
  normalizedWord: string;
  cueText: string;
  videoId: string;
  videoTitle: string;
  videoUrl: string;
  createdAt: string;
}

/**
 * 本地存储的根 schema。design §10。
 */
export interface StorageSchema {
  settings: UserSettings;
  vocabulary: VocabularyItem[];
  schemaVersion: number;
}

export const DEFAULT_SETTINGS: UserSettings = {
  enabled: true,
  showTargetCaption: false,  // 默认关闭,用户按 S 开启 nosub 字幕
  showTranslatedCaption: false,
  targetLanguage: 'en',
  translationLanguage: 'zh-CN',
  interfaceLanguage: 'auto',
  dictionarySource: 'public',
};

export const CURRENT_SCHEMA_VERSION = 3;
