/**
 * SessionController —— design §3.1, tasks T09。
 *
 * 中央协调器:持有 player / caption adapters / 播放状态。
 * 对外暴露"意图"(requestLoopBack/requestNext/...)和只读 ViewState。
 * UI 和键盘控制器不直接碰播放器,只通过此 Controller。
 *
 * 不负责:
 * - 循环调度的高频轮询(T10 PlaybackEngine)
 * - DOM 事件绑定(T11 KeyboardController)
 * - UI 渲染(T12)
 *
 * Controller 自身用 FakePlayerAdapter 可完整测试(design §13.2)。
 */

import type { PlayerAdapter } from '../youtube/player-adapter.js';
import type { CaptionAdapter } from '../youtube/caption-adapter.js';
import type { CaptionTrack, Cue, UserSettings } from '../shared/types.js';
import { DEFAULT_SETTINGS } from '../shared/types.js';
import {
  createSession,
  handleAKey,
  handleDKey,
  handleQKey,
  handleMediaChange,
  handleUserSeek,
  isUserSeek,
  markInternalSeek,
  updateActiveCue,
  type ListeningSession,
} from '../playback/playback-state.js';
import { findCurrentCue } from '../playback/cue-index.js';
import { logger } from '../shared/logger.js';
import type { Scheduler } from '../playback/playback-engine.js';
import { rafScheduler } from '../playback/playback-engine.js';
import { TranslationService } from '../assistance/translation-service.js';
import { GoogleTranslateProvider } from '../assistance/providers/google-translate-provider.js';
import { BaiduTranslateProvider } from '../assistance/providers/baidu-translate-provider.js';
import { YandexTranslateProvider } from '../assistance/providers/yandex-translate-provider.js';
import { resolveLocale, t, type AppLocale } from '../shared/i18n.js';

const log = logger.createLogger('controller');

/** F 键循环的播放速率 */
const PLAYBACK_RATES: number[] = [1.0, 0.8, 0.6];

/** S 键字幕揭示挡位 */
export type RevealLevel = 0 | 1 | 2;
// 0 = 隐藏(normal 无 / loop 白块), 1 = 字幕, 2 = 字幕+翻译

/** UI 订阅的派生状态。design §8.2。 */
export interface ViewState {
  status: 'loading' | 'ready' | 'unsupported' | 'error';
  activeCue?: Cue;
  isRepeating: boolean;
  /** S 键挡位: 0=隐藏 1=首字母 2=完整 3=完整+翻译 */
  revealLevel: RevealLevel;
  /** 翻译是否已配置 (有 TranslationProvider 且能返回结果) */
  translationAvailable: boolean;
  /** 当前播放速率 */
  playbackRate: number;
  interfaceLanguage: AppLocale;
  /** undefined while account status is loading. */
  isPro?: boolean;
  /** Google 翻译不可用时, 推荐的区域兜底方案 */
  translationSuggestion?: { name: string; label: string } | null;
  errorMessage?: string;
}

export type ViewStateListener = (state: ViewState) => void;

export type AnalyticsInputMethod = 'keyboard' | 'toolbar';
export type CoreActionResult =
  | 'enter_focused_listening'
  | 'exit_focused_listening'
  | 'repeat_current'
  | 'previous_cue'
  | 'show_original'
  | 'show_translation'
  | 'hide_subtitles'
  | 'next_cue'
  | 'exit_loop';

export interface CoreActionOutcome {
  action: 'Q' | 'A' | 'S' | 'D';
  actionResult: CoreActionResult;
  inputMethod: AnalyticsInputMethod;
}

export type CaptionFailureReason =
  | 'metadata_timeout'
  | 'no_usable_tracks'
  | 'track_load_failed'
  | 'empty_track';

export type SessionInitResult =
  | { status: 'ready'; languageCode: string; isAutoGenerated: boolean }
  | { status: 'failed'; failureReason: CaptionFailureReason };

export class SessionController {
  private player: PlayerAdapter;
  private captions: CaptionAdapter;
  private session: ListeningSession | null = null;
  private track: CaptionTrack | null = null;
  private settings: UserSettings = { ...DEFAULT_SETTINGS };
  private listeners = new Set<ViewStateListener>();
  private actionListeners = new Set<(outcome: CoreActionOutcome) => void>();
  /** 字幕 ticker:正常播放时用 rAF 跟踪当前 cue(T12 字幕组件) */
  private tickerId: number | null = null;
  /** 翻译服务 */
  private translation: TranslationService;
  /** S 键挡位: 正常和循环各记各的 */
  private normalLevel: RevealLevel = 0;
  private loopLevel: RevealLevel = 0;
  private proAccess: boolean | null = null;
  private lastView: ViewState = {
    status: 'loading',
    isRepeating: false,
    revealLevel: 0,
    translationAvailable: false,
    playbackRate: 1,
    interfaceLanguage: 'en',
  };

  constructor(
    player: PlayerAdapter,
    captions: CaptionAdapter,
    private readonly scheduler: Scheduler = rafScheduler,
    translation?: TranslationService,
  ) {
    this.player = player;
    this.captions = captions;
    this.translation = translation ?? new TranslationService([
      new GoogleTranslateProvider(),
      new BaiduTranslateProvider(),
      new YandexTranslateProvider(),
    ]);
    // 订阅播放器 seek 事件,判定是否用户主动拖动
    this.player.subscribe((event) => {
      if (event.type === 'seek') {
        this.handleSeekEvent(event.currentTimeMs);
      }
    });
    // 从存储加载用户配置的翻译 API Key
    this.loadTranslationCredentials();
  }

  /** 从 chrome.storage 加载自定义翻译 API Key (仅 Pro) */
  private loadTranslationCredentials(): void {
    if (typeof chrome === 'undefined' || !chrome.storage) return;
    chrome.storage.local.get(['translationKeys', 'proAccess'], (result) => {
      const isPro = result.proAccess === true;
      if (!isPro) return; // 免费用户只能用 Google Translate
      const keys = result.translationKeys as Record<string, string> | undefined;
      if (!keys) return;
      for (const p of this.translation.getProviders()) {
        if (p.name === 'baidu' && keys.baiduAppId && keys.baiduSecret) {
          (p as BaiduTranslateProvider).setCredentials(keys.baiduAppId, keys.baiduSecret);
        }
        if (p.name === 'yandex' && keys.yandexKey) {
          (p as YandexTranslateProvider).setApiKey(keys.yandexKey);
        }
      }
    });
  }

  /** 初始化:加载字幕轨道 */
  async init(videoId: string, captionsMetadataReady = true): Promise<SessionInitResult> {
    log.info('init: videoId', videoId);
    const locale = resolveLocale(this.settings.interfaceLanguage);
    (this.captions as { setLocale?: (l: AppLocale) => void }).setLocale?.(locale);
    this.emit({ status: 'loading', isRepeating: false, revealLevel: 0, translationAvailable: this.isTranslationAvailable(), playbackRate: this.player.getPlaybackRate(), interfaceLanguage: locale });

    if (!this.captions.isAvailable()) {
      log.warn('init: captions.isAvailable() 返回 false → unsupported');
      this.emit({ status: 'unsupported', isRepeating: false, revealLevel: 0, translationAvailable: false, playbackRate: 1, interfaceLanguage: locale, errorMessage: t('videoHasNoCaptions', locale) });
      return {
        status: 'failed',
        failureReason: captionsMetadataReady ? 'no_usable_tracks' : 'metadata_timeout',
      };
    }

    try {
      const tracks = await this.captions.listTracks();
      log.debug('init: listTracks 返回', tracks.length, '条');
      if (tracks.length === 0) {
        log.warn('init: listTracks 为空 → unsupported');
        this.emit({ status: 'unsupported', isRepeating: false, revealLevel: 0, translationAvailable: false, playbackRate: 1, interfaceLanguage: locale, errorMessage: t('videoHasNoCaptions', locale) });
        return { status: 'failed', failureReason: 'no_usable_tracks' };
      }
      const preferred = (this.settings.targetLanguage ?? 'en').toLowerCase();
      const selected = tracks.find((track) => track.languageCode.toLowerCase() === preferred)
        ?? tracks.find((track) => track.languageCode.toLowerCase().startsWith(`${preferred}-`))
        ?? tracks.find((track) => track.languageCode.toLowerCase().startsWith('en'))
        ?? tracks[0];
      const loaded = await this.captions.loadTrack(selected.id, videoId);
      if (loaded.cues.length === 0) {
        log.warn('init: 字幕轨为空 → unsupported');
        this.emit({ status: 'unsupported', isRepeating: false, revealLevel: 0, translationAvailable: false, playbackRate: 1, interfaceLanguage: locale, errorMessage: t('videoHasNoCaptions', locale) });
        return { status: 'failed', failureReason: 'empty_track' };
      }
      this.track = loaded;
      this.session = createSession(videoId, loaded.id, loaded.cues);
      log.info('init: 就绪, cue 数', loaded.cues.length);
      this.startTicker(); // 启动字幕跟踪
      this.emit(this.deriveState());
      return {
        status: 'ready',
        languageCode: loaded.languageCode,
        isAutoGenerated: loaded.isAutoGenerated,
      };
    } catch (e) {
      log.error('init: 加载失败', (e as Error).message);
      this.emit({ status: 'error', isRepeating: false, revealLevel: 0, translationAvailable: false, playbackRate: 1, interfaceLanguage: locale, errorMessage: t('captionLoadFailed', locale) });
      return { status: 'failed', failureReason: 'track_load_failed' };
    }
  }

  /** Q 键：进入或退出精听模式。 */
  toggleFocusedListening(inputMethod: AnalyticsInputMethod = 'keyboard'): void {
    if (!this.session) return;
    const wasRepeating = this.session.mode.kind === 'repeat';
    const now = this.player.getCurrentTimeMs();
    const { session, intent } = handleQKey(this.session, now);
    if (intent.type === 'none') return;
    this.session = session;
    if (intent.type === 'seek' && typeof intent.targetMs === 'number') {
      this.session = markInternalSeek(this.session, intent.targetMs, Date.now());
    }
    this.emitAction({
      action: 'Q',
      actionResult: wasRepeating ? 'exit_focused_listening' : 'enter_focused_listening',
      inputMethod,
    });
    this.emit(this.deriveState());
  }

  /** A 键：精听中返回上一句。 */
  requestLoopBack(inputMethod: AnalyticsInputMethod = 'keyboard'): void {
    if (!this.session) return;
    const repeatedCueId = this.session.mode.kind === 'repeat' ? this.session.mode.cueId : null;
    const { session, intent } = handleAKey(this.session);
    if (intent.type === 'none') return;
    this.session = session;
    // 每次进入循环或切到前一句时, 重置挡位为隐藏(0)
    if (this.session.mode.kind === 'repeat') {
      this.loopLevel = 0;
    }
    if (intent.type === 'seek' && typeof intent.targetMs === 'number') {
      this.session = markInternalSeek(this.session, intent.targetMs, Date.now());
      this.emitAction({
        action: 'A',
        actionResult: repeatedCueId !== this.session.activeCueId
          ? 'previous_cue'
          : 'repeat_current',
        inputMethod,
      });
    }
    log.debug('requestLoopBack: mode=', this.session.mode.kind);
    this.emit(this.deriveState());
  }

  /** D 键：下一句；精听中切句后继续保持精听。 */
  requestNext(inputMethod: AnalyticsInputMethod = 'keyboard'): void {
    if (!this.session) return;
    const { session, intent } = handleDKey(this.session);
    this.session = session;
    // requestNext 不依赖 PlaybackEngine(退出循环,engine 收到 stopLoop),
    // 所以这里自己执行 seek。
    if (intent.type === 'seek' && typeof intent.targetMs === 'number') {
      if (intent.markInternal) {
        this.session = markInternalSeek(this.session, intent.targetMs, Date.now());
      }
      this.player.seekToMs(intent.targetMs);
      void this.player.play();
    }
    if (intent.type === 'seek') {
      this.emitAction({ action: 'D', actionResult: 'next_cue', inputMethod });
    }
    this.emit(this.deriveState());
  }

  /** 意图:S 键 — 循环挡位 0→1→2→3→0 */
  toggleReveal(inputMethod: AnalyticsInputMethod = 'keyboard'): void {
    if (!this.session) return;
    const repeating = this.session.mode.kind === 'repeat';
    const current = repeating ? this.loopLevel : this.normalLevel;
    const next = ((current + 1) % 3) as RevealLevel;
    if (repeating) this.loopLevel = next;
    else this.normalLevel = next;
    this.emit(this.deriveState());
    const actionResult: CoreActionResult = next === 1
      ? 'show_original'
      : next === 2 ? 'show_translation' : 'hide_subtitles';
    this.emitAction({ action: 'S', actionResult, inputMethod });
    // 到挡位 2 时, 预加载当前 cue 翻译
    const activeLevel = this.session?.mode.kind === 'repeat' ? this.loopLevel : this.normalLevel;
    if (activeLevel === 2 && this.session?.activeCueId) {
      this.prefetchTranslations(this.session.activeCueId);
    }
  }

  /** 意图:切换播放速度(对应 F 键)。循环 1.0 → 0.8 → 0.6 → 1.0 */
  togglePlaybackRate(): void {
    const current = this.player.getPlaybackRate();
    const idx = PLAYBACK_RATES.indexOf(current);
    const next = PLAYBACK_RATES[(idx + 1) % PLAYBACK_RATES.length];
    this.player.setPlaybackRate(next);
    log.debug('playbackRate:', current, '→', next);
    this.emit(this.deriveState());
  }

  /** 播放器 seek 事件处理:判定是用户拖动还是插件内部 seek */
  private handleSeekEvent(seekedTimeMs: number): void {
    if (!this.session) return;
    const now = Date.now();
    const isUser = isUserSeek(this.session, seekedTimeMs, now);
    if (isUser) {
      const { session, intent } = handleUserSeek(this.session, seekedTimeMs);
      if (session === this.session && intent.type === 'none') {
        return; // session 未变且无意图:不 emit,避免触发 startLoop 重入
      }
      this.session = session;
      this.applyIntent(intent);
      this.emit(this.deriveState());
    }
  }

  /**
   * 由 PlaybackEngine(T10)周期调用,更新 active cue。
   * 也可由 controller 自己的定时器驱动(此处留接口,T10 实现)。
   */
  onTick(currentTimeMs: number): void {
    if (!this.session) return;
    const prevCueId = this.session.activeCueId;
    const updated = updateActiveCue(this.session, currentTimeMs);
    if (updated !== this.session) {
      this.session = updated;
      this.emit(this.deriveState());
      // active cue 变了 → 预加载翻译(不管当前挡位, 提前准备)
      const newCueId = this.session.activeCueId;
      if (newCueId && newCueId !== prevCueId) {
        this.prefetchTranslations(newCueId);
      }
    }
  }

  /**
   * 执行状态机产生的意图(副作用)。
   * 标记内部 seek、seek 播放器、播放。
   */
  private applyIntent(intent: { type: string; targetMs?: number; markInternal?: boolean }): void {
    if (intent.type === 'seek' && typeof intent.targetMs === 'number') {
      // 先标记内部 seek,再执行(标记窗口覆盖即将触发的 seek 事件)
      if (intent.markInternal && this.session) {
        this.session = markInternalSeek(this.session, intent.targetMs, Date.now());
      }
      this.player.seekToMs(intent.targetMs);
      void this.player.play();
    }
    // exitLoop / cleanup / none:无播放器副作用
  }

  /** 从 session + settings 派生只读 ViewState */
  private deriveState(): ViewState {
    if (!this.session || !this.track) {
      return {
        status: 'loading',
        isRepeating: false,
        revealLevel: this.getActiveLevel(),
        translationAvailable: this.isTranslationAvailable(),
        playbackRate: this.player.getPlaybackRate(),
        interfaceLanguage: resolveLocale(this.settings.interfaceLanguage),
        isPro: this.proAccess ?? undefined,
        translationSuggestion: this.getTranslationSuggestion(),
      };
    }
    const activeCueId = this.session.activeCueId;
    const activeCue = activeCueId ? this.track.cues.find((c) => c.id === activeCueId) : undefined;
    return {
      status: 'ready',
      activeCue,
      isRepeating: this.session.mode.kind === 'repeat',
      revealLevel: this.getActiveLevel(),
      translationAvailable: this.isTranslationAvailable(),
      playbackRate: this.player.getPlaybackRate(),
      interfaceLanguage: resolveLocale(this.settings.interfaceLanguage),
      isPro: this.proAccess ?? undefined,
      translationSuggestion: this.getTranslationSuggestion(),
    };
  }

  /** 翻译失败时给出区域兜底建议 */
  private getTranslationSuggestion(): { name: string; label: string } | null | undefined {
    // 只在 Google 刚失败 且 没有其他 provider 可用时建议
    if (!this.translation.wasGoogleJustFailed()) return undefined;
    const rec = TranslationService.recommendProvider(
      resolveLocale(this.settings.interfaceLanguage),
    );
    return rec ? { name: rec.name, label: rec.label } : null;
  }

  /** 当前活跃的挡位(正常 vs 循环) */
  private getActiveLevel(): RevealLevel {
    return this.session?.mode.kind === 'repeat' ? this.loopLevel : this.normalLevel;
  }

  /** 订阅 ViewState 变化 */
  subscribe(listener: ViewStateListener): () => void {
    this.listeners.add(listener);
    return () => {
      this.listeners.delete(listener);
    };
  }

  subscribeToCoreActions(listener: (outcome: CoreActionOutcome) => void): () => void {
    this.actionListeners.add(listener);
    return () => this.actionListeners.delete(listener);
  }

  private emitAction(outcome: CoreActionOutcome): void {
    for (const listener of this.actionListeners) listener(outcome);
  }

  /** 当前 ViewState(快照,返回最后一次 emit 的状态) */
  getState(): ViewState {
    return this.lastView;
  }

  /** 当前 session(供 T10 PlaybackEngine 使用) */
  getSession(): ListeningSession | null {
    return this.session;
  }

  /** 当前轨道 */
  getTrack(): CaptionTrack | null {
    return this.track;
  }

  /** 返回当前句附近的字幕窗口，供词典低优先级预取。 */
  getCueWindow(centerCueId: string, before = 5, after = 15): Cue[] {
    if (!this.track) return [];
    const center = this.track.cues.findIndex((cue) => cue.id === centerCueId);
    if (center < 0) return [];
    return this.track.cues.slice(
      Math.max(0, center - Math.max(0, before)),
      Math.min(this.track.cues.length, center + Math.max(0, after) + 1),
    );
  }

  /** 更新设置(T13 持久化加载时调用) */
  updateSettings(settings: Partial<UserSettings>): void {
    this.settings = { ...this.settings, ...settings };
    this.normalLevel = this.settings.showTranslatedCaption
      ? 2
      : this.settings.showTargetCaption ? 1 : 0;
    this.emit(this.deriveState());
  }

  /** Apply the account entitlement loaded by the extension background. */
  setProAccess(isPro: boolean): void {
    this.proAccess = isPro;
    this.emit(this.deriveState());
    // 用户可能在账号状态返回前已切到翻译挡；确认 Pro 后立即加载。
    if (isPro && this.getActiveLevel() === 2 && this.session?.activeCueId) {
      this.prefetchTranslations(this.session.activeCueId);
    }
  }

  private isTranslationAvailable(): boolean {
    return this.settings.translationLanguage !== 'off' && this.translation.hasProvider();
  }

  /** 销毁会话(视频/轨道变更) */
  dispose(): void {
    this.stopTicker();
    this.translation.clearCache();
    const result = handleMediaChange();
    this.session = result.session;
    this.track = null;
    this.listeners.clear();
    this.actionListeners.clear();
  }

  // ---- 翻译 ----

  /** 预加载范围:当前 cue 前后各多少条 */
  private static readonly PREFETCH_RANGE = 10;

  /**
   * 预翻译当前 cue 前后各 N 条。
   * 当前 cue 优先,其余后台静默加载。
   */
  private prefetchTranslations(centerCueId: string): void {
    if (!this.track || this.proAccess !== true || !this.isTranslationAvailable()) return;

    const cues = this.track.cues;
    const centerIdx = cues.findIndex((c) => c.id === centerCueId);
    if (centerIdx < 0) return;

    const range = SessionController.PREFETCH_RANGE;
    const start = Math.max(0, centerIdx - range);
    const end = Math.min(cues.length - 1, centerIdx + range);

    // 逐条翻译(TranslationService 内部有缓存,已翻译的秒返回)
    for (let i = centerIdx; i <= end; i++) {
      void this.translateOne(cues[i]);
    }
    for (let i = centerIdx - 1; i >= start; i--) {
      void this.translateOne(cues[i]);
    }
  }

  /** 翻译单条 cue,成功/失败后如果是 active cue 则重新 emit */
  private async translateOne(cue: Cue): Promise<void> {
    if (cue.translatedText || cue.translationFailed || this.proAccess !== true || !this.isTranslationAvailable()) return;

    try {
      const result = await this.translation.translate({
        text: cue.text,
        sourceLanguage: this.settings.targetLanguage ?? 'en',
        targetLanguage: this.settings.translationLanguage ?? 'zh-CN',
      });
      if (result) {
        cue.translatedText = result.translatedText;
        cue.translationFailed = undefined;
      } else {
        cue.translationFailed = '翻译服务不可用';
      }
      if (this.session?.activeCueId === cue.id) {
        this.emit(this.deriveState());
      }
    } catch (err) {
      const msg = (err as Error).message || '';
      cue.translationFailed = msg.includes('timeout') || msg.includes('Timeout')
        ? '网络超时'
        : msg.includes('429') || msg.includes('Too Many')
          ? '翻译请求过频, 请稍候'
          : '网络连接失败';
      log.warn('translateOne failed:', msg);
      if (this.session?.activeCueId === cue.id) {
        this.emit(this.deriveState());
      }
    }
  }

  // ---- 字幕 ticker ----

  /** 启动正常播放时的字幕跟踪(rAF 轮询 active cue) */
  private startTicker(): void {
    if (this.tickerId !== null) return; // 幂等
    const tick = (): void => {
      if (this.tickerId === null) return; // 已停止
      this.onTick(this.player.getCurrentTimeMs());
      this.tickerId = this.scheduler.requestFrame(tick);
    };
    this.tickerId = this.scheduler.requestFrame(tick);
  }

  /** 停止字幕跟踪 */
  private stopTicker(): void {
    if (this.tickerId !== null) {
      this.scheduler.cancelFrame(this.tickerId);
      this.tickerId = null;
    }
  }

  private emit(state: ViewState): void {
    this.lastView = state;
    for (const listener of this.listeners) {
      try {
        listener(state);
      } catch {
        // 单个监听器异常不影响其他(design §13.2)
      }
    }
  }
}

export { findCurrentCue };
