import { describe, it, expect } from 'vitest';
import {
  toTrackSummary,
  trackIdOf,
  pickPreferredTrack,
  parseTranscriptResponse,
} from '../../src/youtube/caption-parser.js';
import type { RawCaptionTrack } from '../../src/shared/types.js';
import sampleResponse from '../fixtures/transcript-response-sample.json' with { type: 'json' };

describe('toTrackSummary / trackIdOf', () => {
  it('ASR 轨道标记 isAutoGenerated=true', () => {
    const raw: RawCaptionTrack = { languageCode: 'en', kind: 'asr', name: 'English (auto)' };
    const s = toTrackSummary(raw, 0);
    expect(s.isAutoGenerated).toBe(true);
    expect(s.id).toBe(trackIdOf('en', true, 0));
  });

  it('人工轨道(kind 缺失)标记 isAutoGenerated=false', () => {
    const raw: RawCaptionTrack = { languageCode: 'en', name: 'English' };
    const s = toTrackSummary(raw, 1);
    expect(s.isAutoGenerated).toBe(false);
    expect(s.id).toBe('track-1-en-manual');
  });

  it('label 缺失时用 languageCode', () => {
    const raw: RawCaptionTrack = { languageCode: 'fr' };
    expect(toTrackSummary(raw, 0).label).toBe('fr');
  });
});

describe('pickPreferredTrack', () => {
  const manual: RawCaptionTrack = { languageCode: 'en', name: 'English' };
  const asr: RawCaptionTrack = { languageCode: 'en', kind: 'asr', name: 'English (auto)' };
  const french: RawCaptionTrack = { languageCode: 'fr', name: 'French' };

  it('同语言优先人工 > ASR', () => {
    const tracks = [asr, manual, french];
    const pick = pickPreferredTrack(tracks, 'en');
    expect(pick?.track).toBe(manual);
  });

  it('只有 ASR 时返回 ASR', () => {
    const tracks = [asr, french];
    const pick = pickPreferredTrack(tracks, 'en');
    expect(pick?.track).toBe(asr);
  });

  it('无匹配语言返回 null', () => {
    const tracks = [french];
    expect(pickPreferredTrack(tracks, 'en')).toBeNull();
  });

  it('空列表返回 null', () => {
    expect(pickPreferredTrack([], 'en')).toBeNull();
  });
});

describe('parseTranscriptResponse', () => {
  it('从真实结构解析出有效 cue', () => {
    const cues = parseTranscriptResponse(sampleResponse);
    // fixture: 4 段, 但第 3 段文本全空白(过滤), 第 4 段 startMs=invalid(过滤)
    expect(cues).toHaveLength(2);
    expect(cues[0]).toEqual({
      startMs: 160,
      endMs: 6879,
      text: 'Hello listeners',
    });
    expect(cues[1]).toEqual({
      startMs: 6879,
      endMs: 13120,
      text: 'this episode',
    });
  });

  it('拼接 runs 文本', () => {
    const resp = {
      actions: [
        {
          updateEngagementPanelAction: {
            content: {
              transcriptRenderer: {
                content: {
                  transcriptSearchPanelRenderer: {
                    body: {
                      transcriptSegmentListRenderer: {
                        initialSegments: [
                          {
                            transcriptSegmentRenderer: {
                              startMs: '0',
                              endMs: '100',
                              snippet: { runs: [{ text: 'a' }, { text: 'b' }, { text: 'c' }] },
                            },
                          },
                        ],
                      },
                    },
                  },
                },
              },
            },
          },
        },
      ],
    };
    expect(parseTranscriptResponse(resp)[0].text).toBe('abc');
  });

  it('空 actions 返回空数组', () => {
    expect(parseTranscriptResponse({})).toEqual([]);
    expect(parseTranscriptResponse({ actions: [] })).toEqual([]);
  });

  it('无 initialSegments 返回空数组', () => {
    expect(parseTranscriptResponse({ actions: [{ updateEngagementPanelAction: {} }] })).toEqual([]);
  });

  it('主路径缺失时走 reloadContinuationItemsCommand 兜底', () => {
    const resp = {
      actions: [
        {
          reloadContinuationItemsCommand: {
            continuationItems: [
              {
                transcriptSegmentRenderer: {
                  startMs: '500',
                  endMs: '1000',
                  snippet: { runs: [{ text: 'fallback' }] },
                },
              },
            ],
          },
        },
      ],
    };
    expect(parseTranscriptResponse(resp)).toEqual([
      { startMs: 500, endMs: 1000, text: 'fallback' },
    ]);
  });

  it('过滤 startMs 非数字的 cue', () => {
    const resp = {
      actions: [
        {
          updateEngagementPanelAction: {
            content: {
              transcriptRenderer: {
                content: {
                  transcriptSearchPanelRenderer: {
                    body: {
                      transcriptSegmentListRenderer: {
                        initialSegments: [
                          {
                            transcriptSegmentRenderer: {
                              startMs: 'bad',
                              endMs: '100',
                              snippet: { runs: [{ text: 'x' }] },
                            },
                          },
                          {
                            transcriptSegmentRenderer: {
                              startMs: '200',
                              endMs: '300',
                              snippet: { runs: [{ text: 'y' }] },
                            },
                          },
                        ],
                      },
                    },
                  },
                },
              },
            },
          },
        },
      ],
    };
    const cues = parseTranscriptResponse(resp);
    expect(cues).toHaveLength(1);
    expect(cues[0].text).toBe('y');
  });
});
