/**
 * FakeCaptionAdapter —— 用于单元/集成测试的可控 CaptionAdapter。
 * design §13.2 要求用假 adapter 验证业务行为。
 */

import type { CaptionAdapter } from '../../src/youtube/caption-adapter.js';
import type { CaptionTrack, CaptionTrackSummary, Cue } from '../../src/shared/types.js';

export class FakeCaptionAdapter implements CaptionAdapter {
  private available: boolean;
  private tracks: CaptionTrack[];
  private shouldFailLoad = false;

  constructor(cues: Cue[] = [], options: { available?: boolean; languageCode?: string } = {}) {
    const lang = options.languageCode ?? 'en';
    this.available = options.available ?? cues.length > 0;
    this.tracks = cues.length > 0
      ? [{
          id: 'track-0-en-manual',
          languageCode: lang,
          label: `${lang}`,
          isAutoGenerated: false,
          cues,
        }]
      : [];
  }

  /** 测试用:让 loadTrack 抛错 */
  failLoadOnNext(): void {
    this.shouldFailLoad = true;
  }

  async listTracks(): Promise<CaptionTrackSummary[]> {
    return this.tracks.map((t) => ({
      id: t.id,
      languageCode: t.languageCode,
      label: t.label,
      isAutoGenerated: t.isAutoGenerated,
    }));
  }

  async loadTrack(trackId: string): Promise<CaptionTrack> {
    if (this.shouldFailLoad) throw new Error('fake load failure');
    const track = this.tracks.find((t) => t.id === trackId);
    if (!track) throw new Error(`track not found: ${trackId}`);
    return track;
  }

  isAvailable(): boolean {
    return this.available;
  }

  async waitForReady(_timeoutMs?: number): Promise<boolean> {
    return this.available; // 假适配器:基于已有数据直接返回
  }

  dispose(): void {
    // 无资源
  }
}
